apiVersion: v1
kind: Service
metadata:
  name: bffweb-svc-lb
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  ports:
  - port: 80  # The service port accessible within the cluster
    targetPort: 80  # The target port on the pod, matching the container port
  selector:
    app: bffweb-ms
