apiVersion: v1
kind: Service
metadata:
  name: bookservice-svc-lb
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  ports:
  - port: 80  # The service port accessible within the cluster
    targetPort: 3000  # The target port on the pod, matching the container port
  selector:
    app: bookservice-ms
